# Generated by Django 4.1.7 on 2023-04-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gr_section',
            field=models.CharField(choices=[('Set', 'SET VALUE'), ('Fatima', '7 - Our Lady of Fatima'), ('Lourdes', '7 - Our Lady of Lourdes'), ('Pillar', '8 - Our Lady of the Pillar'), ('Penafrancia', '8 - Our Lady of Penafrancia'), ('Loreto', '9 - Our Lady of Loreto'), ('Miraculous', '9 - Our Lady of the Miraculous Medal'), ('Holy', '10 - Our Lady of the Holy Rosary'), ('Assumption', '10 - Our Lady of the Assumption'), ('Consolacion', '11 - Our Lady of the Consolacion'), ('Guadalupe', '11 - Our Lady of Guadalupe'), ('Candles', '11 - Our Lady of Candles'), ('Immaculate', '12 - Our Lady of the Immaculate Conception'), ('Carmel', '12 - Our Lady of Mt. Carmel'), ('Angels', '12 - Our Lady of the Angels')], default='Set', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='middle_initial',
            field=models.CharField(max_length=2, verbose_name='Middle initial'),
        ),
    ]
