# Generated by Django 4.1.7 on 2023-04-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_customuser_gr_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.IntegerField(default='0', verbose_name='Balance'),
        ),
    ]
