# Generated by Django 4.1.7 on 2023-04-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_customuser_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='uid',
            field=models.CharField(default='A1A1A1A1', max_length=8, verbose_name='RFID'),
        ),
    ]
