# Generated by Django 4.1.7 on 2023-04-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_customuser_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
