# Generated by Django 4.1.7 on 2023-04-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_customuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.FileField(null=True, upload_to='id_pictures/'),
        ),
    ]
