# Generated by Django 4.1.7 on 2023-05-04 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='modules/')),
                ('grade_section', models.CharField(choices=[('Set', 'SET VALUE'), ('Grade 7 - Our Lady of Fatima', '7 - Our Lady of Fatima'), ('Grade 7 - Our Lady of Lourdes', '7 - Our Lady of Lourdes'), ('Grade 8 - Our Lady of the Pillar', '8 - Our Lady of the Pillar'), ('Grade 8 - Our Lady of the Penafrancia', '8 - Our Lady of Penafrancia'), ('Grade 9 - Our Lady of Loreto', '9 - Our Lady of Loreto'), ('Grade 9 - Our Lady of the Miraculous Medal', '9 - Our Lady of the Miraculous Medal'), ('Grade 10 - Our Lady of the Holy Rosary', '10 - Our Lady of the Holy Rosary'), ('Grade 10 - Our Lady of the Assumption', '10 - Our Lady of the Assumption'), ('Grade 11 - Our Lady of the COnsolacion', '11 - Our Lady of the Consolacion'), ('Grade 11 - Our Lady of Guadalupe', '11 - Our Lady of Guadalupe'), ('Grade 11 - Our Lady of the Candles', '11 - Our Lady of Candles'), ('Grade 12 - Our Lady of the Immaculate Conception', '12 - Our Lady of the Immaculate Conception'), ('Grade 12 - Our Lady of Mt. Carmel', '12 - Our Lady of Mt. Carmel'), ('Grade 12 - Our Lady of the Angels', '12 - Our Lady of the Angels')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
