# Generated by Django 4.1.7 on 2023-05-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0010_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_sections',
            field=models.CharField(blank=True, choices=[], max_length=50, verbose_name='Assigned Sections'),
        ),
    ]
