# Generated by Django 4.1.7 on 2023-05-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0016_alter_customuser_gr_section_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='subject',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
