# Generated by Django 4.1.7 on 2023-05-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0020_section_grade_section_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='section',
            name='section',
        ),
    ]
