# Generated by Django 4.1.7 on 2023-05-09 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0024_alter_customuser_gr_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gr_section',
            field=models.ForeignKey(default='Set', on_delete=django.db.models.deletion.PROTECT, to='sites.section'),
        ),
    ]
