# Generated by Django 4.1.7 on 2023-05-09 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0029_remove_module_grade_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='assigned_sections',
        ),
    ]
