# Generated by Django 4.1.7 on 2023-05-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0030_remove_customuser_assigned_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='attached_phone',
            field=models.CharField(default='+631234567890', max_length=13),
        ),
    ]
